{
 "title": "Custom Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job='node-exporter',mode='idle'}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((1 - node_filesystem_avail_bytes{fstype!='tmpfs'}/node_filesystem_size_bytes{fstype!='tmpfs'})*100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": " Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "legendFormat": "{{device}}" },
    { "expr": "node_arp_entries", "legendFormat": "{{device}}" }
   ]
  }
 ]
}